### ISSUE TITLE
Wrong signatures for ELF and PE in the default userdb.ini file.

### ISSUE THREAD

**Issue by D4R30** [SudoerUser/FileID#1]
At _src/userdb.ini_ you entered not just the magics of the binaries, but also other stuff in headers **(EI_CLASS, EI_VERSION, ...).** This would cause the program to wrongly compare the signature and if someone with a 32-bit binary uses your program, the program would not recognize the signature.
I've attached the fixed _userdb.ini_. 
Good luck.
[userdb.txt](https://github.com/SudoerUser/FileID/files/6775222/userdb.txt)

**Comment by SudoerUser** [comment]
Thank you for your opinion. In fact, this is a test example of what is going to exist. In the future, a large number of signatures are to be added to the file. I edited the file anyway. Good luck.
